Resources:
Ec2Instance:
  Type: "AWS::EC2::Instance"
  Properties:
    SecurityGroups:
      - !Ref InstanceSecurityGroup
    KeyName: devops
    ImageId: "ami-06e54d05255faf8f6" # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
InstanceSecurityGroup:
  Type: "AWS::EC2::SecurityGroup"
  Properties:
    GroupDescription: Enable access via ports
    SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: "22"
        ToPort: "22"
        CidrIp: 0.0.0.0/0
