version: 2.1
commands:
  print_pipeline_id:
    description: "Print out an ID number"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
  run_yarn_install:
    description: "Install dependencies"
    steps:
      - run: npm install
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            npm run lint
            npm build
      - print_pipeline_id

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run_yarn_install
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run_yarn_install
      - print_pipeline_id

  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create cloudformation stack
          command: |
            aws cloudformation deploy --stack-name ciDeploy --template-file template.yml --region us-west-2
workflows:
  build-deploy:
    jobs:
      # - build
      # - test:
      #     requires: [build]
      # - analyze:
      #     requires: [test]
      - deploy:
          filters:
            branches:
              only: master
