version: 2.1
commands:
  print_pipeline_id:
    description: "Print out an ID number"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
  run_yarn_install:
    description: "Install dependencies"
    steps:
      - run: npm install
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
            npm run lint
            npm build
      - print_pipeline_id
      # - run: yarn build > ~/
      # - persist_to_workspace:
      #     root: ~/
      #     paths:
      #       - build
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # - attach_workspace:
      #     at: ~/
      - run_yarn_install
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      # - attach_workspace:
      #     at: ~/
      - run_yarn_install
      - run: |
          npm audit fix
          npm audit

workflows:
  covid-19-ci:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
